### ISSUE TITLE
OAuth and '/me' support

### ISSUE THREAD

**Issue by jonsgreen** [Clever/clever-ruby#102]
I am surprised that there is no support here for the '/me' request and maybe also the code/token OAuth request flow. I can easily make these requests separately in my app but it seems like these would be desirable features for this gem. 

I might be able to submit a PR for this but I am wondering if there is some reason this is not being supported and whether such a PR might be accepted.

**Comment by sandiegoscott** [comment]
I also have the same question. Nowhere on the Clever site is code for the OAuth sequence including the /me request, or obtaining an access token. Could save a lot of time for someone not familiar with OAuth like myself.
