### ISSUE TITLE
`get_events` and `get_events_with_http_info` fail for invalid state

### ISSUE THREAD

**Issue by geoffharcourt** [Clever/clever-ruby#106]
I am trying to fetch information for some districts for an ongoing events sync, and am getting the following exception:

```
ArgumentError: invalid value for 'state', must be one of ["running", "pending", "error", "paused"].
```

I can make the API call successfully in the API Explorer, so I think this might be a failure when the `state` is validated while building a `districts.updated` response. I can see that some districts appear to have had SIS sync issues where they had or have a state of `success`, which doesn't fit the four types named there, which then causes a validation error.

Here's one of the events I suspect is causing the problem, I've redacted technical details but am happy to share in a private channel:

```json
{
      "data": {
        "type": "districts.updated",
        "data": {
          "object": {
            "last_sync": "2018-09-17T04:57:10.690Z",
            "pause_start": "2018-05-30",
            "launch_date": "2018-04-16",
            "mdr_number": "[redacted]",
            "nces_id": "[redacted]",
            "pause_end": "2018-08-01",
            "name": "[redacted]",
            "state": "success",
            "sis_type": "skyward-api",
            "error": "",
            "id": "[redacted]"
          },
          "previous_attributes": {
            "error": "The data in your most recent sync has changed significantly.  To prevent unintended loss of data, we have not processed this sync.  Please review the \"Action Required: Clever Sync on Hold\" email to resolve this hold.",
            "state": "pending"
          }
        },
        "created": "2018-09-19T19:37:18.800Z",
        "id": "[redacted]"
      },
      "uri": "/v2.0/events/[redacted]"
    },
```

**Comment by meliaj** [comment]
Apologies for not closing the loop here sooner - our eng team resolved this issue in early October and since then, moving forward, we will only output the expected values ["running", "pending", "error", "paused"].  If you see anything different, please let us know.
