### ISSUE TITLE
Relax json gem requirement

### ISSUE THREAD

**Issue by shidel-dev** [Clever/clever-ruby#107]
The JSON gem carries with it native C extensions, that require a compiler toolchain be present on any machine that installs it.

Ruby carries the following JSON gem versions with the distribution by default:

JSON 1.4.2 with 1.9.2 - https://github.com/ruby/ruby/blob/ruby_1_9_2/ext/json/lib/json/version.rb
JSON 1.5.5 with 1.9.3 - https://github.com/ruby/ruby/blob/ruby_1_9_3/ext/json/lib/json/version.rb
JSON 1.7.7 with 2.0.0 series - https://github.com/ruby/ruby/blob/ruby_2_0_0/ext/json/lib/json/version.rb
JSON 1.8.1 with 2.1.0 - through 2.1.7 - https://github.com/ruby/ruby/blob/v2_1_7/ext/json/lib/json/version.rb
JSON 1.8.1 with 2.2.0 - through 2.2.3 - https://github.com/ruby/ruby/blob/v2_2_3/ext/json/lib/json/version.rb
JSON 2.1.0 with 2.5.1
https://github.com/ruby/ruby/blob/v2_5_1/ext/json/lib/json/version.rb

I believe that the way that the json gem dep is being specified in the gemspec file could be relaxed with no ill effects. The way it is currently forces people running newer ruby versions to install an older version of a gem which is now part of the standard lib.

I would suggest removing this dep all together as it is only necessary to support older ruby versions `1.8.*` which are not being widely deployed anymore. The other option would be to make the version specification just `>= 1.8`.

**Comment by meliaj** [comment]
Thanks for your suggestion! We have some users that I believe are still on Ruby 1.8, so I will look into changing the version specification.

**Comment by geoffharcourt** [comment]
(bumping this issue)

Hi @meliaj, Rubies older than 2.3.x are EOL and no longer supported, so I think it should be safe to move on. (Ruby 1.8 was EOLed in late 2014.)

**Comment by meliaj** [comment]
@geoffharcourt @shidel-dev is this blocking you from using the gem?

As I said before, I think we have some users still on Ruby 1.8 so I am reluctant to remove this entirely until I can confirm that, or I would just change the Ruby version specification to be  `>= 1.8`.

**Comment by shidel-dev** [comment]
I would suggest making the specification read '>=1.8' and '<3' so that users of newer ruby versions (the vast majority people using this gem) can easily use the bundled version of the json gem that comes with ruby 2.0+. The newer versions of the json gem are more performant, have bug fixes, and security patches. this is the strategy used by much more widely deployed gem which support ruby 1.8 for example https://github.com/colszowka/simplecov/blob/master/simplecov.gemspec#L19

**Comment by geoffharcourt** [comment]
I think @shidel-dev's suggestion would be flexible enough to allow the current known Ruby versions to use their json version of choice without locking out older Rubies.
