### ISSUE TITLE
Don't use global Clever object

### ISSUE THREAD

**Issue by osdiab** [Clever/clever-ruby#65]
Right now methods are called against `Clever` rather than an instance of `Clever`. As a result configuration changes in one place can impact it elsewhere, making testability a bit harder, usage of the library less flexible, and leaking the Clever object globally. Require an instance of Clever rather than referring to it statically.

**Comment by osdiab** [comment]
Using https://github.com/twilio/twilio-ruby as inspiration. Many Ruby API libraries seem to depend on global state, while that behavior may be idiomatic I'm not convinced we ought to follow that particular idiom; Twilio bucks that trend while still maintaining similarities to it.

**Comment by joelmccracken** [comment]
:+1:

**Comment by joshlory** [comment]
Any movement on this issue?  We'd like to use separate OAuth tokens per teacher, to give them access to classes they own on Clever.  Thanks!
