### ISSUE TITLE
No API resource for StudentContact, but Clever has StudentContact events

### ISSUE THREAD

**Issue by TheJefe** [Clever/clever-ruby#74]
Clever added StudentContact events to their event stream, but clever-ruby has no idea how to handle these new events because their isn't a APIResource defined for it yet.

**Comment by joelmccracken** [comment]
We currently work around this in our code base like this:

```
        # Clever sometimes sends us events that the clever-ruby gem
        # doesn't know how to handle. For these cases we should catch
        # and bugsnag rather then kill the entire event stream
        begin
          clever_object_class = clever_event.object.class
        rescue NoMethodError => e
          raise e unless e.message =~ /linked_resources/
          Bugsnag.notify(e)
          return
        end
```

**Comment by Christopher-Bradshaw** [comment]
@TheJefe, sorry for the delayed response. We have moved to a community supported model with our client libraries and are happy to review and merge any PR's you have made in your codebase to fix this. Else if you do not need the contacts, @joelmccracken's workaround seems reasonable.
