### ISSUE TITLE
Clever Event Subclasses - NameError: uninitialized constant Clever::SchoolsCreated::CleverAPI

### ISSUE THREAD

**Issue by jedspurg** [Clever/clever-ruby#86]
It looks like a namespace changed recently occurred and the subclasses of ``Event`` were missed. 

The ``_deserialize`` method of each ``Event`` subclass (i.e., ``SchoolsCreated``) still reference ``CleverAPI``. This needs to change to ``Clever``. Better yet, the subclasses don't really need to override this method. As far as I can tell, they add no new functionality and the parent class of ``Event`` is properly referencing ``Clever`` instead of ``CleverAPI``.

**Comment by bpina** [comment]
looks like this was addressed in https://github.com/Clever/clever-ruby/pull/88
