### ISSUE TITLE
Problem with connecting to the API v1.1 using 0.14.0 

### ISSUE THREAD

**Issue by kamilbednarz** [Clever/clever-ruby#89]
Hello there,

Two days ago (07/11) we started having issues with getting an `events` feed using ver. `0.13.2` (also confirmed to be a problem in `0.14.0`). The same code used to work until then.

The error message is the following:
```
Clever::APIError: Invalid response object from API: "Cannot GET //v1.1/events?starting_after=some-id-that-I-replaced-here" (HTTP response code was 404)
from /home/vagrant/.rvm/gems/ruby-2.1.8/gems/clever-ruby-0.14.0/lib/clever-ruby.rb:294:in `rescue in handle_api_error'
```

It looks like for some of the requests the gem constructs the path with double slash in the beginning. I'm not sure what have changed on the backend side, but apparently it no longer supports the requests constructed by this gem.

**Comment by kamilbednarz** [comment]
If somebody also has this problem, here is a monkey patch that solves that:

`config/initializers/clever.rb`: 
```ruby
module Clever
  class << self
    def create_payload(method, url, params)
      case method.to_s.downcase.to_sym
      when :get, :head, :delete
      url_obj = URI.parse(url)
        if url_obj.query
          params = CGI.parse(url_obj.query).map { |k, v| { k => v[0] } }.reduce(:merge).merge params
        end
        url_obj.query = convert_to_query_string params
 
        # Start of the monkey patch
        # Apparently, the way how this gem constructs URI paths to the API is no longer
        # supported by their servers. It constructs sometimes paths that start with
        # '/v1/events' instead of 'v1/events'. After concatenating that with the API url
        # that ends with a slash, we end up having double slashes in the path.
        url_obj.path.gsub!('//', '/')
        # End of the monkey patch
 
        url = url_obj.to_s
        payload = nil
      else
        payload = params
      end
      [url, payload]
    end
  end
end
```

**Comment by drhurd** [comment]
@kamilbednarz Thanks for filing this! You are correct, this was resulting in 404s. However, it was due to a configuration error on our end. We've resolved the configuration issue and this should no longer be a problem.

I'm going to close this issue. Feel free to re-open if you think we should address the double-slash issue.

**Comment by kamilbednarz** [comment]
Thank you! 

If this works on the API service end, I think there is no need to fix it in the gem.
