### ISSUE TITLE
Bug In Events API: event's type and id missing

### ISSUE THREAD

**Issue by sur** [Clever/clever-ruby#92]
Event's type and id metadata missing for the events like SutdentsCreated and StudentsDeleted

**Comment by meliaj** [comment]
Thanks for pointing this out! I've merged a fix for this. I will publish a new version in the next few days that also address some other issues.

**Comment by sur** [comment]
Thanks for quickly looking into this @meliaj 

Can you please take a look at the #91 as well and possibly fix with the above changes.

The #91 is basically when you try to fetch the student contacts via get_contacts_for_student API call, it always returns blank no matter if the student have contacts or not.

**Comment by sur** [comment]
@meliaj Can you please confirm that the type and id are also fixed for Students.Deleted and Updated events as well ?

Thanks.

**Comment by meliaj** [comment]
I believe Students.Updated and Students.Deleted always worked. They have the same attributes. Let me know if this is not the case.

I also have a PR open for #91
